CREATE SEQUENCE seq_academy;
CREATE SEQUENCE seq_course;
CREATE SEQUENCE seq_takecourse;

CREATE TABLE IF NOT EXISTS user ( 
 id varchar(30) not null primary key,
 password varchar(30) not null,
 user_name varchar(40) not null,
 age varchar(3),
 phone varchar(30),
 user_type varchar(1) not null
);

CREATE TABLE IF NOT EXISTS academy ( 
 code integer generated by default as sequence seq_academy primary key,  
 academy_name varchar(40) not null,
 phone varchar(30) not null,
 address varchar(100) not null
);

CREATE TABLE IF NOT EXISTS course ( 
 code integer generated by default as sequence seq_course primary key,  
 course_name varchar(40) not null,
 user_num integer default '0',
 academy_code integer not null
);

CREATE TABLE IF NOT EXISTS takecourse ( 
 code integer generated by default as sequence seq_takecourse primary key,  
 user_id varchar(30) not null,
 course_code integer not null
);


INSERT INTO user (id, password, user_name, age, phone, user_type)
VALUES ('admin', 'admin', '관리자', '99', '010-9999-9999', 'M');

INSERT INTO user (id, password, user_name, age, phone, user_type)
VALUES ('test', '1234', '테스트', '26', '010-1234-1234', 'A');

INSERT INTO academy (academy_name, phone, address)
VALUES ('BitSchool', '02-3486-3456', '서울특별시 서초구 서초동 1327-33 비트빌 3층');

INSERT INTO academy (academy_name, phone, address)
VALUES ('삼성SDS멀티캠퍼스', '1588-3357', '서울특별시 강남구 역삼동 707-19');

INSERT INTO course (course_name, academy_code)
VALUES ('Spring', '0');

INSERT INTO course (course_name, academy_code)
VALUES ('XML', '0');

INSERT INTO course (course_name, academy_code)
VALUES ('JAVA', '0');

INSERT INTO takecourse (user_id, course_code)
VALUES ('test', '0');

UPDATE course SET user_num = user_num + 1 
WHERE code = '0';
